"""add_nome_oferta_em_transacoes_e_assinaturas

Revision ID: 04a31709c5d5
Revises: 888a27ca45e3
Create Date: 2025-08-01 18:40:49.192064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a31709c5d5'
down_revision: Union[str, None] = '888a27ca45e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assinaturas', sa.Column('nome_oferta', sa.String(length=255), nullable=True))
    op.add_column('transacoes', sa.Column('nome_oferta', sa.String(length=255), nullable=True))
    op.drop_constraint('transacoes_id_transacao_origem_key', 'transacoes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transacoes_id_transacao_origem_key', 'transacoes', ['id_transacao_origem'])
    op.drop_column('transacoes', 'nome_oferta')
    op.drop_column('assinaturas', 'nome_oferta')
    # ### end Alembic commands ###
