"""add tipo_recusa em transacoes

Revision ID: 279d522bc3b5
Revises: 711fd3d6b2a7
Create Date: 2025-07-16 19:56:53.043406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279d522bc3b5'
down_revision: Union[str, None] = '711fd3d6b2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('tipo_recusa', sa.String(length=50), nullable=True))
    # Removido: alteração de assinatura_id para NOT NULL
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacoes', 'tipo_recusa')
    # ### end Alembic commands ###
