"""Permitir assinatura_id nulo em transacoes

Revision ID: 5b36431818f0
Revises: 36b2b96ae8a5
Create Date: 2025-07-02 19:35:39.143453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b36431818f0'
down_revision: Union[str, None] = '36b2b96ae8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('transacoes', 'assinatura_id',
        existing_type=sa.Integer(),
        nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('transacoes', 'assinatura_id',
        existing_type=sa.Integer(),
        nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
