"""add valor_bruto e valor_liquido em transacoes

Revision ID: 74e8bc0d6085
Revises: fd744422a86c
Create Date: 2025-07-03 18:52:23.893857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e8bc0d6085'
down_revision: Union[str, None] = 'fd744422a86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
