"""permitir assinatura_id nulo em transacoes

Revision ID: 888a27ca45e3
Revises: d7aa261b61fc
Create Date: 2025-07-17 18:38:41.192585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888a27ca45e3'
down_revision: Union[str, None] = 'd7aa261b61fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacoes', 'assinatura_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacoes', 'assinatura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
