"""add produto_nome em transacoes

Revision ID: d7aa261b61fc
Revises: 279d522bc3b5
Create Date: 2025-07-17 14:18:44.199680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7aa261b61fc'
down_revision: Union[str, None] = '279d522bc3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('produto_nome', sa.String(length=255), nullable=True))
    op.alter_column('transacoes', 'assinatura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacoes', 'assinatura_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
